<?php
/* Start Main EN Language Pack */

$IndexLang = array(
'IndexTitle'		=> 'Index',
'LatestScores' 	=> 'Latest Scores',
'TopHeadlines' 	=> 'Top Headlines',
'NoHeadlines' 	=> 'No Headlines',
'LatestTransactions'		=> 'Latest Trade, Waiver, Injury & Suspension Transactions',
'News'		=> ' News',
'By'		=> ' By',
'On'		=> ' On',
'Top5Point'		=> ' Top 5 Points',
'Top5Goal'		=> ' Top 5 Goals',
'Top5Goalies'		=> ' Top 5 Goalies',
'Top5Defenseman'		=> ' Top 5 Defenseman',
'Top5Rookies'		=> ' Top 5 Rookies',
'Top20FreeAgents'		=> 'Top 20 Free Agents',
'Viewcomments'		=> 'View comments',
'Comment'		=> 'New Comment',
'7DaysStar'		=> 'Last Week 3 Star',
'30DaysStar'		=> 'Last Month 3 Star',
'ProGamesDaysStar'		=> 'Today Pro 3 Star',
'FarmGamesDaysStar'		=> 'Today Farm 3 Star',
'NextGames' 	=> 'Next Games',
'BoxScore'		=> 'BoxScore',
);

$NewsLang = array(
'LeagueNews'		=> 'League News',
'NewsFrom'	=> 'News From : ',
'NewsTitle'			=> 'News Title : ',
'News'			=> 'News : ',
'Save'			=> 'Save',
'LeagueManagement'			=> 'Commissioner',
'Guest'			=> 'Guest',
'EditNews'			=> 'Edit News',
'CreateNews'			=> 'Create News',
'CreateComment'			=> 'Create Comment',
'EditComment'			=> 'Edit Comment',
'LeagueNewsManagement'		=> 'League News Management',
'ReturnLeagueNewsManagementPage'		=> 'Return League News Management Page',
'Time'			=> 'Time',
'By'			=> 'By',
'Title'			=> 'Title',
'Action'			=> 'Action',
'Erase'			=> 'Erase',
'EditErase'			=> 'Edit or Erase',
'Password'			=> 'Password : ',
'WasErase'			=> ' was erased from the database.',
'ErrorErase'			=> 'An error occurred while deleting!',
'SaveSuccessfully'		=> 'News Saved Successfully!',
'IncorrectPassword'			=> 'Incorrect Password!',
'IllegalAction'			=> 'Illegal Action!',
'TeamNotePassword1'		=> 'If you can’t find a Team Name in the « News From » drop box, it’s because the team has no password configured in the STHS.', 
'TeamNotePassword2'		=> 'The league commissioner can create, edit or delete news on behalf of Team with the League Web Password.',
'Comment' => 'Comment #',
'CreateNewsDatabase' => 'Create News Database!',
'CreateNewsDatabaseDone' => 'News Database Created!',
'MassDeletion' => 'How many old news do you wish to delete? : ',
'MassDelete' => 'Launch Mass Deletion',
'MassDeleteWarning' => 'You can’t undo this action!',
'MassDeleteSuccess1'=> 'Successfully delete ',
'MassDeleteSuccess2'=> ' old news.',
'ReturnLeagueNewsManagement' => 'Return to League News Management',
);

$WebClientLang = array(
'Title'		=> 'Team\'s Web Client Roster and Lines Editor',
'Team'		=> 'Team',
'Roster'		=> 'Roster',
'ProLines'		=> 'Pro Lines',
'FarmLines'		=> 'Farm Lines',
'TeamInfo'		=> 'Team Information',
'Edit'		=> 'Edit',
'SubmitCapAss'		=> 'Submit Captain & Assistants Change',
'SubmitTicket'		=> 'Submit Ticket Price Change',
'ErrorCap'	=>	'Incorrect captain and/or assistant value. Either it is empty, or the same players have been selected twice.',
'ErrorProTicket'	=>	'Pro Ticket price incorrect. Level 1 must be the highest and level 4 the lowest.',
'ErrorFarmTicket'	=>	'Farm Ticket price incorrect. Level 1 must be higher than level 2.',
'EditConfirm'		=> 'Edit Confirm!',
'EditFail'		=> '<span style="color:red">Fail Editing!</span>',
'EditPlayer'		=> 'Edit Players Information',
);

$SendEmailLang = array(
'Title'		=> ' Send Today\'s Information to General Manager',
'IncorrectPassword'			=> 'Incorrect Password!',
'EmailSend'			=> 'Email Send to ',
'Emailwillbesend'			=> 'Email will be sent to ',
'Password'			=> 'League Password : ',
'SendEmail'			=> 'Send Email',
'NoInformation'			=> 'No Information to Send',
'Note1'			=> 'Send multiple emails may take time. Please be patient.',
'Note2'			=> 'The Send Email Function is dependent on the configuration that website hosting company provides you. The \'Hide Email and IM Address from Output\' must not be checked in the STHS.',
'LinktoBoxscore' 			=>   'Link to Boxscore',
'DebugMode' 			=>   'Debug Mode',
);

$UploadLang = array(
'UploadLine'			=> 'Upload Lines',
'UploadFile'			=> 'Upload File',
'UploadFileWebsite'			=> 'Upload Website File',
'FileFormat'			=> 'Sorry, only STHS files are allowed.',
'FileSize'			=> 'Sorry, your file is too small or too large.',
'NotUpload'			=> 'Sorry, your file was not uploaded.',
'Error'			=> 'Sorry, there was an error uploading your file.',
'WrongTeamFile'			=> 'Sorry, your file doesn\'t have the correct name for your team.',
'TheFile'			=> 'The file ',
'BeenUploaded'			=> ' has been uploaded.',
'Selectfile'			=> 'Select file to upload',
);

$TradeLang = array(
'Trade'			=> 'Trade',
'Players'		=> 'Players',
'Error'			=> 'Sorry, there was an error.',
'Team'		=> 'Team',
'Team1'		=> 'Team making an offer',
'Team2'		=> 'Team receiving an offer',
'Prospects'			=> 'Prospects',
'DraftPicks'			=> 'Draft Picks',
'DraftPicksCon'			=> 'Conditional Draft Picks',
'Money'			=> 'Money',
'SalaryCapY1'			=> 'Salary Cap Year #1',
'SalaryCapY2'			=> 'Salary Cap Year #2',
'MessageWhy'			=> 'Message to Commissioner',
'Submit'		=> 'Submit',
'ConfirmSubmit'			=> 'Confirm Trade',
'Confirm'			=> 'Confirmed Trade',
'RefuseSubmit'			=> 'Refuse Trade',
'Refuse'			=> 'Trade Refused',
'Fail'			=> ' <span style="color:red">Issue adding item to the trade!</span>',
'ConfirmTradeAlreadyEnter'			=> 'Confirmed Trade Already Enter by First GM',
'To'		=> 'To : ',
'From'		=> 'From : ',
'TradeOffer'		=> ' / Trade Offer',
'CreateOffer'		=> 'Create Offer',
'NoTrade'		=> 'No Trade to Confirm for ',
'PendingTrade'		=> 'There is pending trade for one of the team. Please confirm or refuse pending trade before creating a new one.',
'ConfirmTrade'		=> 'Confirm Trades',
'ViewConfirmTrade'		=> 'View Confirm Trades',
'ViewConfirmTradeNotFound'		=> 'There is no trade confirm.',
'PendingTrade'		=> 'Pending Trades',
'ViewPendingTrade'		=> 'View Pending Trades',
'ViewPendingTradeNotFound'		=> 'There is no pending trade.',
'FailPlayerUpdate'			=> 'Fail Player Update in Database',
'TradeDeadline'		=> 'Trade Deadline has passed!',
'IllegalAction'			=> 'Illegal Action!',
);

$DraftSelectionLang = array(
'EntryDraftSelection'			=> 'Entry Draft Selection',
'AvailablesProspects'			=> 'Availables Prospects',
'AvailablesPlayers'			=> 'Availables Players',
'Selection'			=> 'Selection',
'FantasyDraftSelection'			=> 'Fantasy Draft Selection',
'Max250DraftSelection'			=> 'A maximum of 250 selection drafts have been saved!',
'DraftSelectionUpdate'			=> 'Draft Selection Update for ',
'FreeAgentFailOffer'			=> ' <span style="color:red">Fail adding offer to the database!</span>',
'SubmitSelection'		=> 'Submit Selection List',
'EraseSelection'		=> 'Erase Selection List',
);

$BoxscoreLang = array(
'BoxscorefromYear'			=> 'Boxscore from Year #',
);

$LeagueInformationLang = array(
'LeagueInformation'			=> 'League Information',
'LeagueOwner'			=> 'League Owner',
'HowToJoinLeague'			=> 'How to Join League',
'LeagueRules'			=> 'League Rules',
);

/* End Main EN Language Pack */
?>