<?php
/* Start Main FR Language Pack */

$IndexLang = array(
'IndexTitle'		=> 'Index',
'LatestScores' 	=> 'Derniers résultats',
'TopHeadlines' 	=> 'Les Manchettes',
'NoHeadlines' 	=> 'Aucune Manchette',
'LatestTransactions'		=> 'Dernières transactions, blessures, suspensions, ballotages',
'News'		=> ' Actualité',
'By'		=> ' Par',
'On'		=> ' Le',
'Top5Point'		=> 'Top 5 Points',
'Top5Goal'		=> 'Top 5 Buts',
'Top5Goalies'		=> 'Top 5 Gardiens',
'Top5Defenseman'		=> 'Top 5 Défenseurs',
'Top5Rookies'		=> 'Top 5 Recrues',
'TopFreeAgents'		=> 'Top 50 Agents libres',
'Viewcomments'		=> 'Voir commentaires',
'Comment'		=> 'Nouveau commentaire',
'7DaysStar'		=> '3 étoiles de la semaine',
'30DaysStar'		=> '3 étoiles du mois',
'ProGamesDaysStar'		=> '3 étoiles de la journée Pro',
'FarmGamesDaysStar'		=> '3 étoiles de la journée Mineure',
'NextGames' 	=> 'Prochains matchs',
'BoxScore'		=> 'Sommaire du match ',
);

$NewsLang = array(
'LeagueNews'		=> 'Nouvelles de la ligue',
'NewsFrom'	=> 'Nouvelle de: ',
'NewsTitle'			=> 'Titre de la nouvelle: ',
'News'			=> 'Nouvelle: ',
'Save'			=> 'Sauvegarder',
'LeagueManagement'			=> 'Commissaire',
'Guest'			=> 'Invité',
'EditNews'			=> 'Éditer une nouvelle',
'CreateComment'			=> 'Créer un commentaire',
'EditComment'			=> 'Editer un commentaire',
'CreateNews'			=> 'Créer une nouvelle',
'LeagueNewsManagement'		=> 'Gestion des nouvelles de la ligue',
'ReturnLeagueNewsManagementPage'		=> 'Retour vers la gestion des nouvelles de la ligue',
'Time'			=> 'Temps',
'By'			=> 'Par',
'Title'			=> 'Titre',
'Action'			=> 'Action',
'Erase'			=> 'Effacer',
'EditErase'			=> 'Éditer ou effacer',
'Password'			=> 'Mot de passe : ',
'WasErase'			=> ' a été effacé de la base de données.',
'ErrorErase'			=> 'Une erreur est survenue lors de l’effacement!',
'SaveSuccessfully'		=> 'Nouvelle enregistrée avec succès!',
'IncorrectPassword'			=> 'Mot de passe incorrect!',
'IllegalAction'			=> 'Action Illégal!',
'TeamNotePassword1'		=> 'Si vous ne pouvez pas trouver le nom d’une équipe dans le menu déroulant «Nouvelles de», c’est parce que l’équipe n’a pas de mot de passe configuré dans le STHS.',
'TeamNotePassword2'		=> 'Le commissaire de la ligue peut créer, modifier ou supprimer des nouvelles au nom de l’équipe avec le mot de passe Web de la ligue.',
'Comment' => 'Commentaire #',
'CreateNewsDatabase' => 'Créer base de données pour les nouvelles de la ligue!',
'CreateNewsDatabaseDone' => 'Base de données pour les nouvelles créé!',
'MassDeletion' => 'Combien de vieille nouvelles voulez-vous effacer? : ',
'MassDelete' => 'Lancer l’effacement de masse',
'MassDeleteWarning' => 'Cette action n’est pas réversible!',
'MassDeleteSuccess1'=> 'L’effacement de ',
'MassDeleteSuccess2'=> ' nouvelles a réussi.',
'ReturnLeagueNewsManagement' => 'Retour à la gestion des nouvelles de la ligue',
);

$WebClientLang = array(
'Title'		=> 'Editeur Web pour les formations et lignes d’équipes',
'Team'		=> 'Équipe',
'Roster'		=> 'Formation',
'ProLines'		=> 'Lignes Pro',
'FarmLines'		=> 'Lignes Mineure',
'TeamInfo'		=> 'Information d\'équipe',
'CurrentPassword'			=> 'Mot de passe Actuel : ',
'NewPassword'			=> 'Nouveau Mot de passe : ',
'ChangeNewPassword'		=> 'Changement du Mot de Passe de l\'utilisateur',
'IncorrectPassword'			=> 'Mot de passe Actuel Incorrect!',
'EditPasswordConfirm'		=> 'Édition du Mot de Passe Confirmé',
'Edit'		=> 'Éditer',
'SubmitCapAss'		=> 'Soumettre Changement Captaine & Assistants',
'SubmitTicket'		=> 'Soumettre Changement Prix des Billets',
'SubmitNewPassword'		=> 'Soumettre Changement du Mot de Passe',
'PasswordSecurityNote'		=> 'NOTE DE SÉCURITÉ : Étant donné que n\'importe qui peut lire la base de données SQLite, votre mot de passe chiffré peut être facilement volé. Déchiffrer votre mot de passe n’est pas une chose facile à faire mais c’est possible. Veuillez donc NE PAS choisir un mot de passe que vous utilisez ailleurs sur Internet (surtout pas pour votre institution financière !). Le STHS n\'impose PAS la complexité ou la longueur des mots de passe.',
'ErrorCap'	=>	'Valeur incorrecte du capitaine et/ou de l\'assistant. Soit il est vide, soit le même joueur a été sélectionné deux fois.',
'ErrorProTicket'	=>	'Prix du billet Pro incorrect. Le niveau 1 doit être le plus élevé et le niveau 4 le plus bas.',
'ErrorFarmTicket'	=>	'Prix du billet Farm incorrect. Le niveau 1 doit être supérieur au niveau 2.',
'EditConfirm'		=> 'Édition Confirmé.',
'EditFail'		=> '<span style="color:red">Échec de l\'édition!</span>',
'EditPlayer'		=> 'Éditer information des joueurs',
);

$SendEmailLang = array(
'Title'		=> ' Envoyer les informations de la journée aux directeurs généraux',
'EmailSend'			=> 'Courriel envoyé à  ',
'Emailwillbesend'			=> 'Un courriel sera envové à ',
'SendEmail'			=> 'Envoyer courriel',
'NoInformation'			=> 'Aucune information à envoyer',
'Note1'			=> 'Envoyer plusieurs courriels peut prendre du temps. S.V.P. soyez patient.',
'Note2'			=> 'La fonction d’envoi de courriel est dépendante de la configuration que votre fournisseur de site Web a configuré. L’option ’Hide Email and IM Address from Output’ ne doit pas être cochée dans le STHS.',
'LinktoBoxscore' 			=>   'Lien vers sommaire du match',
'DebugMode' 			=>   'Mode Débogage',
);

$UploadLang = array(
'UploadLine'			=> 'Envoyer un alignement',
'UploadFile'			=> 'Envoyer un fichier',
'UploadFileWebsite'			=> 'Envoyer un fichier pour le site web',
'FileFormat'			=> 'Désolé, seuls les fichiers STHS sont autorisés.',
'FileSize'			=> 'Désolé, votre fichier est trop petit ou trop volumineux.',
'NotUpload'			=> 'Désolé, votre fichier n’a pas été envoyé.',
'Error'			=> 'Désolé, une erreur s’est produite lors de l\'envoi de votre fichier.',
'TheFile'			=> 'Le fichier ',
'WrongTeamFile'			=> 'Désolé, votre fichier n\'a pas le bon nom pour votre équipe.',
'BeenUploaded'			=> ' a été envoyé.',
'Selectfile'			=> 'Sélectionnez le fichier à envoyer',
);

$TradeLang = array(
'Trade'			=> 'Échange',
'Players'		=> 'Joueurs',
'Error'			=> 'Désolé, une erreur s’est produite.',
'Team'		=> 'Équipe',
'Team1'		=> 'Équipe faisant une offre',
'Team2'		=> 'Équipe recevant une offre',
'Prospects'			=> 'Espoirs',
'DraftPicks'			=> 'Choix au repêchage',
'DraftPicksCon'			=> 'Choix au repêchage conditionnel',
'Money'			=> 'Argent',
'SalaryCapY1'			=> 'Plafond salarial année #1',
'SalaryCapY2'			=> 'Plafond salarial année #2',
'MessageWhy'			=> 'Message au Commissaire',
'Submit'		=> 'Soumettre',
'ConfirmSubmit'			=> 'Confirmer l’échange',
'Confirm'			=> 'Échange confirmé',
'RefuseSubmit'			=> 'Refuser l’échange',
'Refuse'			=> 'Échange refusé',
'Fail'			=> ' <span style="color:red">Un item n’a pas été ajouté à l’échange!</span>',
'ConfirmTradeAlreadyEnter'			=> 'Confirmer l’échange déjà entré par un autre DG',
'To'		=> 'À : ',
'From'		=> 'De : ',
'TradeOffer'		=> ' / Échange offert',
'CreateOffer'		=> 'Créez une offre',
'NoTrade'		=> 'Aucun échange à confirmer pour le ',
'PendingTrade'		=> 'Il y a un échange en attente pour une équipe. Veuillez confirmer ou refuser l’échange avant d’en créer un nouveau.',
'ConfirmTrade'		=> 'Échanges confirmés',
'ViewConfirmTrade'		=> 'Afficher les échanges confirmés',
'ViewConfirmTradeNotFound'		=> 'Aucun échange confirmé.',
'PendingTrades'		=> 'Échanges en attentes',
'ViewPendingTrade'		=> 'Afficher les échanges en attentes',
'ViewPendingTradeNotFound'		=> 'Aucun échange en attente.',
'FailPlayerUpdate'			=> 'Échec de mise à jour du joueur dans la base de données',
'TradeDeadline'		=> 'La date limite d’échange est passée!',
'IllegalAction'			=> 'Action Illégal!',
);

$DraftSelectionLang = array(
'EntryDraftSelection'			=> 'Selection pour le repêchage amateur',
'AvailablesProspects'			=> 'Espoirs disponibles',
'AvailablesPlayers'			=> 'Joueurs disponible',
'Selection'			=> 'Sélection',
'FantasyDraftSelection'			=> 'Sélection pour le repêchage de fantaisie',
'Max250DraftSelection'			=> 'Le maximum de 250 sélection a été enregistré!',
'DraftSelectionFail'			=> ' <span style="color:red">Échec de la mise à jour de sélection de repêchage à la base de données. Vos données sont perdu!</span>',
'DraftSelectionUpdate'			=> 'Sélection repêchage mise à jour pour ',
'SubmitSelection'		=> 'Soumettre sélection repêchage',
'EraseSelection'		=> 'Effacer sélection repêchage',
);

$BoxscoreLang = array(
'BoxscorefromYear'			=> 'Match de l\'année #',
);

$LeagueInformationLang = array(
'LeagueInformation'			=> 'Information sur la Ligue',
'LeagueOwner'			=> 'Propriétaire de la Ligue',
'HowToJoinLeague'			=> 'Comment rejoindre la Ligue',
'LeagueRules'			=> 'Règlement de la Ligue',
);

/* End Main FR Language Pack */
?>